
diction = {'_links': {'next': {'href': 'https://api.edamam.com/api/food-database/v2/parser?session=44&app_key=69d004c3e3c5b967261e625baea627fc&app_id=85b409cf&ingr=steak',
                     'title': 'Next page'}},
 'hints': [{'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_aregbrwb5q7z2db1h14uxaizfd9f',
                     'image': 'https://www.edamam.com/food-img/4d2/4d2ae7e6fd2145d4c89a8ffae7d4f2b7.jpg',        
                     'knownAs': 'steak',
                     'label': 'Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 228.0,
                                   'FAT': 15.8,
                                   'FIBTG': 0.0,
                                   'PROCNT': 20.0},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_t_bone_steak'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 461.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 1359.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 461.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_aregbrwb5q7z2db1h14uxaizfd9f',
                     'image': 'https://www.edamam.com/food-img/4d2/4d2ae7e6fd2145d4c89a8ffae7d4f2b7.jpg',        
                     'knownAs': 'steak',
                     'label': 'Beef Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 228.0,
                                   'FAT': 15.8,
                                   'FIBTG': 0.0,
                                   'PROCNT': 20.0},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_t_bone_steak'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 461.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 1359.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 461.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_aregbrwb5q7z2db1h14uxaizfd9f',
                     'image': 'https://www.edamam.com/food-img/4d2/4d2ae7e6fd2145d4c89a8ffae7d4f2b7.jpg',        
                     'knownAs': 'steak',
                     'label': 't Bone Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 228.0,
                                   'FAT': 15.8,
                                   'FIBTG': 0.0,
                                   'PROCNT': 20.0},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_t_bone_steak'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 461.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 1359.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 461.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_abhe6ejbfw25i1a4u0iiwbi0aw6s',
                     'image': 'https://www.edamam.com/food-img/f8d/f8dedaeb7292857a4d92019961fb91fb.jpg',        
                     'knownAs': 'flank steak',
                     'label': 'Flank Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 165.0,
                                   'FAT': 8.29,
                                   'FIBTG': 0.0,
                                   'PROCNT': 21.2},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_flank_steak'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 202.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 202.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_b7cf8o4aicxm3iajpfjm4b6vcmnx',
                     'image': 'https://www.edamam.com/food-img/841/841b64894944db7d9c4a5472cc439eea.jpg',        
                     'knownAs': 'round steak',
                     'label': 'Round Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 168.0,
                                   'FAT': 8.19,
                                   'FIBTG': 0.0,
                                   'PROCNT': 21.9},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_round_steak'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 170.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 1132.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 170.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_aifm62daw1i6txalya881bcetyzn',
                     'image': 'https://www.edamam.com/food-img/4f1/4f10105d5c8178f25590ca6dfcd37fca.jpg',        
                     'knownAs': 'sirloin steak',
                     'label': 'Filet Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 214.0,
                                   'FAT': 14.3,
                                   'FIBTG': 0.0,
                                   'PROCNT': 19.9},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_sirloin_steak'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 340.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 1359.0},
                         {'label': 'Sirloin',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_sirloin',
                          'weight': 453.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 340.0},
                         {'label': 'Burger',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_burger',
                          'weight': 142.0},
                         {'label': 'Hamburger',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_hamburger',
                          'weight': 142.0},
                         {'label': 'Pattie',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pattie',
                          'weight': 142.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0},
                         {'label': 'Cup',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_cup',
                          'weight': 227.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_bc31067bzd5dr0bmfsa42ahrv3uk',
                     'image': 'https://www.edamam.com/food-img/29a/29a37c7597b9b5c39abd22df3769da06.jpg',        
                     'knownAs': 'beef rib steak',
                     'label': 'Rib Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 260.0,
                                   'FAT': 21.0,
                                   'FIBTG': 0.0,
                                   'PROCNT': 17.9},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_rib_steak'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 456.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 2674.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 456.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_agvdl6pajjrz8sbghz0cdaz6q4yf',
                     'image': 'https://www.edamam.com/food-img/e1d/e1dc9aaf420f55f30dd24768e532594a.jpg',        
                     'knownAs': 'skirt steak',
                     'label': 'Hanger Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 195.0,
                                   'FAT': 12.8,
                                   'FIBTG': 0.0,
                                   'PROCNT': 20.1},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_skirt_steak'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 388.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 388.0},
                         {'label': 'Strip',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_strip',
                          'weight': 28.35},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_bwbjyozb6nminjbvtqrwnawt5rnc',
                     'image': 'https://www.edamam.com/food-img/a74/a74f4d1a191fdf11e28bf8de1f6a95dd.jpg',        
                     'knownAs': 'porterhouse steak',
                     'label': 'Porterhouse Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 218.0,
                                   'FAT': 14.6,
                                   'FIBTG': 0.0,
                                   'PROCNT': 20.4},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_porterhouse_steak'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 539.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 1132.5},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 539.0},
                         {'label': 'Piece',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_piece',
                          'weight': 85.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_bd2spt5bdl3k04bvjq3j3botp4r6',
                     'image': 'https://www.edamam.com/food-img/e53/e53f909f06b1a44972b9492a7604beee.jpg',        
                     'knownAs': 'chuck steak',
                     'label': 'Chuck Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 227.0,
                                   'FAT': 16.8,
                                   'FIBTG': 0.0,
                                   'PROCNT': 18.9},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#food_chuck_steak'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 382.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 1359.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 382.0},
                         {'label': 'Fillet',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_fillet',
                          'weight': 227.0},
                         {'label': 'Tender',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_tender',
                          'weight': 227.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_alxxpp4bxuehrfbu4itz9aq8i5tz',
                     'image': 'https://www.edamam.com/food-img/94f/94f4e30c497ac1c382fce5889c9d34c9.jpg',        
                     'knownAs': 'beef shoulder center steak',
                     'label': 'Clod Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 143.0,
                                   'FAT': 6.12,
                                   'FIBTG': 0.0,
                                   'PROCNT': 20.4},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_shoulder_center_steak'},      
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 246.0},
                         {'label': 'Clod',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_clod',
                          'weight': 2265.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 2265.0},
                         {'label': 'Shoulder',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_shoulder',
                          'weight': 2265.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 246.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_a1qm1qga3rhbanbowi34ja6x6xyl',
                     'image': 'https://www.edamam.com/food-img/818/818522f7f285ce65fd11f956d119cb50.jpg',        
                     'knownAs': 'beef top loin steak',
                     'label': 'Striploin Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 237.0,
                                   'FAT': 17.1,
                                   'FIBTG': 0.0,
                                   'PROCNT': 19.3},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_top_loin_steak'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 301.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 1359.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 301.0},
                         {'label': 'Loin',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_loin',
                          'weight': 283.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_a6skwpab6vneclb6altplagex1id',
                     'image': 'https://www.edamam.com/food-img/8e6/8e6e6cf8da34183518c2a052b21bb764.jpg',        
                     'knownAs': 'top sirloin cap steak',
                     'label': 'Cap Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 199.0,
                                   'FAT': 13.4,
                                   'FIBTG': 0.0,
                                   'PROCNT': 19.7},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_top_sirloin_cap_steak'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 238.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 238.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_bl7ug3bbssyf9tbfnat2eard4it7',
                     'image': 'https://www.edamam.com/food-img/79d/79deccf2af1c19e68043eaea6f84ae05.jpg',        
                     'knownAs': 'beef shoulder top blade steak',
                     'label': 'Blade Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 152.0,
                                   'FAT': 7.94,
                                   'FIBTG': 0.0,
                                   'PROCNT': 20.1},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_shoulder_top_blade_steak'},   
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 231.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 1359.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 231.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_ahrnkf5bxfenl5be5a071bkc3740',
                     'image': 'https://www.edamam.com/food-img/28f/28f2c7d960e01ff18685b6680ee5a150.jpg',        
                     'knownAs': 'boneless beef rib eye steak',
                     'label': 'Ribeye Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 253.0,
                                   'FAT': 20.0,
                                   'FIBTG': 0.0,
                                   'PROCNT': 18.4},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_boneless_beef_rib_eye_steak'},     
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 350.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 2124.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 350.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_bybx3yoaj0j30aa2d62sxbo973p4',
                     'image': 'https://www.edamam.com/food-img/bee/beeb393a511bf368940476d4c26c0f2b.jpg',        
                     'knownAs': 'lean beef t-bone steak',
                     'label': 'Lean Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 215.0,
                                   'FAT': 14.2,
                                   'FIBTG': 0.0,
                                   'PROCNT': 20.3},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_lean_beef_t_bone_steak'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 458.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 1359.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 458.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_a9esz60a6378pnbbo2xjdaenyjmy',
                     'image': 'https://www.edamam.com/food-img/6e4/6e4187447a4066a470583b949687180d.jpg',        
                     'knownAs': 'arm chuck roast',
                     'label': 'Rump Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 249.0,
                                   'FAT': 18.6,
                                   'FIBTG': 0.0,
                                   'PROCNT': 19.1},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_arm_chuck_roast'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 1801.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 1801.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 340.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_bknby1la98smrsbwnthinbam42nj',
                     'image': 'https://www.edamam.com/food-img/bab/bab88ab3ea40d34e4c8ae35d6b30344a.jpg',        
                     'knownAs': 'beef',
                     'label': 'Stewing Steak',
                     'nutrients': {'CHOCDF': 0.12,
                                   'ENERC_KCAL': 130.0,
                                   'FAT': 4.81,
                                   'FIBTG': 0.0,
                                   'PROCNT': 21.6},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_chuck'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 340.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 1359.0},
                         {'label': 'Fillet',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_fillet',
                          'weight': 340.0},
                         {'label': 'Piece',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_piece',
                          'weight': 85.0},
                         {'label': 'Slice',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_slice',
                          'weight': 57.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0},
                         {'label': 'Cup',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_cup',
                          'weight': 140.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_bjmsdjya61mlu9al7fg1zbw0h28y',
                     'image': 'https://www.edamam.com/food-img/808/80855e62b43698e73a867c4d44581158.jpg',        
                     'knownAs': 'boneless chuck roast',
                     'label': 'California Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 202.0,
                                   'FAT': 13.9,
                                   'FIBTG': 0.0,
                                   'PROCNT': 19.2},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_under_blade_pot_roast'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 949.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 949.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 648.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_bhr4xdgbfo8uimbdynzhnbhej1gg',
                     'image': 'https://www.edamam.com/food-img/1d4/1d4f053f3686725b7d2a92a8320df28b.jpg',        
                     'knownAs': 'veal sirloin',
                     'label': 'Veal Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 152.0,
                                   'FAT': 7.81,
                                   'FIBTG': 0.0,
                                   'PROCNT': 19.1},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_veal_sirloin'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 340.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 2265.0},
                         {'label': 'Sirloin',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_sirloin',
                          'weight': 340.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 340.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_au8m3zia67rlqoavmsp0cbvzhwiq',
                     'image': 'https://www.edamam.com/food-img/f70/f70890fe73fc9e333aa584a88a61e351.jpg',        
                     'knownAs': 'beef tenderloin',
                     'label': 'Tenderloin Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 246.0,
                                   'FAT': 17.9,
                                   'FIBTG': 0.0,
                                   'PROCNT': 19.8},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_tenderloin_steak'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 177.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 1359.0},
                         {'label': 'Tenderloin',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_tenderloin',
                          'weight': 1359.0},
                         {'label': 'Fillet',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_fillet',
                          'weight': 226.8},
                         {'label': 'Loin',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_loin',
                          'weight': 226.8},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 177.0},
                         {'label': 'Medallion',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_medallion',
                          'weight': 113.4},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]},
           {'food': {'category': 'Generic foods',
                     'categoryLabel': 'food',
                     'foodId': 'food_ab1yhvlae9wnimabebeipb2yld3p',
                     'image': 'https://www.edamam.com/food-img/e2b/e2b1076f865b72a507f8cb79be34de2c.jpg',        
                     'knownAs': 'beef triangle',
                     'label': 'Triangle Steak',
                     'nutrients': {'CHOCDF': 0.0,
                                   'ENERC_KCAL': 174.0,
                                   'FAT': 9.51,
                                   'FIBTG': 0.0,
                                   'PROCNT': 20.6},
                     'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_triangle'},
            'measures': [{'label': 'Whole',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_unit',
                          'weight': 271.0},
                         {'label': 'Steak',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_steak',
                          'weight': 453.0},
                         {'label': 'Roast',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_roast',
                          'weight': 271.0},
                         {'label': 'Gram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_gram',
                          'weight': 1.0},
                         {'label': 'Ounce',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_ounce',
                          'weight': 28.349523125},
                         {'label': 'Pound',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_pound',
                          'weight': 453.59237},
                         {'label': 'Kilogram',
                          'uri': 'http://www.edamam.com/ontologies/edamam.owl#Measure_kilogram',
                          'weight': 1000.0}]}],
 'parsed': [{'food': {'category': 'Generic foods',
                      'categoryLabel': 'food',
                      'foodId': 'food_aregbrwb5q7z2db1h14uxaizfd9f',
                      'image': 'https://www.edamam.com/food-img/4d2/4d2ae7e6fd2145d4c89a8ffae7d4f2b7.jpg',       
                      'knownAs': 'steak',
                      'label': 'Steak',
                      'nutrients': {'CHOCDF': 0.0,
                                    'ENERC_KCAL': 228.0,
                                    'FAT': 15.8,
                                    'FIBTG': 0.0,
                                    'PROCNT': 20.0},
                      'uri': 'http://www.edamam.com/ontologies/edamam.owl#Food_beef_t_bone_steak'}}],
 'text': 'steak'}



print(diction["hints"][0]["food"]["image"])